name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Deploy public GHCR image to Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: node-hello-world
        resourceGroup: my-container-app-rg
        imageToDeploy: ghcr.io/ric-cde/node-hello:latest
        registryUrl: ghcr.io
    
